name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.14.3
      - scikit-learn==1.5.2
      - pandas==2.2.2
      - numpy==2.0.2
      - matplotlib==3.9.2
